# Test the best model accuracy in the Kaggle competition
print(test.shape)

# When engineering features there may be also the target column
if 'SalePrice' in test.columns:
    test.drop(columns=['SalePrice'], inplace=True)

# Predict
y_hat = fitted_model.predict(test)

# Check the length
print(len(y_hat))

# Save the prediction
with open('automl-submission.csv', 'w') as file:
    pd.DataFrame({'Id' : test.index.to_list(), 'SalePrice': y_hat}).to_csv(file, index=False)

# Set the enviroment variables and submit the prediction to competition
os.environ['KAGGLE_USERNAME'] = "lubomrstraka"
os.environ['KAGGLE_KEY'] = "c7347462ef834e6645ce238c2f2fa561"
! kaggle competitions submit -c house-prices-advanced-regression-techniques -f automl-submission.csv -m "Submission generated by Azure Automated ML."

# >2021-07-23: Your submission scored 0.13612, which is not an improvement of your best score (0.12481).
# >2021-07-28: Your submission scored 0.13699, which is not an improvement of your best score (0.12481).
# >2021-08-03: Your submission scored 0.13706, which is not an improvement of your best score (0.12481).